# SPDX-FileCopyrightText: 2021 k4leg <python.bogdan@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

core:
  editor: nvim

data:
  email: python.bogdan@gmail.com
  signingKey: DBD9F071BA9ED452

font:
  monospace: JetBrains Mono
