# SPDX-FileCopyrightText: 2021 k4leg <python.bogdan@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

core:
  terminal: kitty
  editor: nvim

data:
  email: python.bogdan@gmail.com
  signingKey: A963D59C96F263DD

font:
  interface: Noto Sans Display
  monospace: JetBrains Mono
