#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 k4leg <python.bogdan@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

. ~/.config/bspwm/lib

run xset r rate 300 30
run setxkbmap us,ru -option grp:caps_toggle,compose:menu
run xinput --set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1
run xinput --set-prop 'SINOWEALTH Game Mouse' 'libinput Accel Profile Enabled' 0, 1
run xinput --set-prop 'SINOWEALTH Game Mouse' 'libinput Accel Speed' -0.7
restart_ xwallpaper --daemon --maximize ~/pictures/backgrounds/dusk.png
run_if_not_running sxhkd
run_if_not_running picom -b
run_if_not_running /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
run_if_not_running dunst
run_if_not_running nm-applet --indicator
run_if_not_running blueman-applet
run_if_not_running flameshot
restart_ polybar top
